import { useState } from 'react'
import './HypothesisBrowser.css'

export interface HypothesisRecord {
  id: string
  scan_id: string
  title: string
  description: string
  confidence: number
  source: string
  status: string
  created_at: string
}

interface Props {
  hypotheses: HypothesisRecord[]
  selectedHypothesis: HypothesisRecord | null
  setSelectedHypothesis: (h: HypothesisRecord | null) => void
}

const STATUS_COLORS: Record<string, string> = {
  GENERATED: '#7c5cbf',
  TESTING:   '#d97706',
  VERIFIED:  '#16a34a',
  REJECTED:  '#dc2626',
}

const SOURCE_LABELS: Record<string, string> = {
  ai:              '🤖 AI',
  csrf_heuristic:  '🔍 CSRF Heuristic',
  unknown:         '❓ Unknown',
}

export default function HypothesisBrowser({ hypotheses, selectedHypothesis, setSelectedHypothesis }: Props) {
  const [filter, setFilter] = useState<string>('ALL')
  const [search, setSearch] = useState('')

  const filtered = hypotheses.filter(h => {
    if (filter !== 'ALL' && h.status !== filter) return false
    if (search && !h.title.toLowerCase().includes(search.toLowerCase()) && !h.description.toLowerCase().includes(search.toLowerCase())) return false
    return true
  })

  const statusCounts = hypotheses.reduce((acc, h) => {
    acc[h.status] = (acc[h.status] || 0) + 1
    return acc
  }, {} as Record<string, number>)

  return (
    <div className="hyp-browser">
      <div className="hyp-header">
        <div className="hyp-title">
          <h2>Hypotheses</h2>
          <span className="hyp-badge">{hypotheses.length} total</span>
        </div>
        <p className="hyp-subtitle">
          AI-generated attack hypotheses. These are unverified and require human review or an active verification step before becoming findings.
        </p>
      </div>

      <div className="hyp-controls">
        <input
          className="hyp-search"
          type="text"
          placeholder="Search hypotheses..."
          value={search}
          onChange={e => setSearch(e.target.value)}
        />
        <div className="hyp-filters">
          {['ALL', 'GENERATED', 'TESTING', 'VERIFIED', 'REJECTED'].map(s => (
            <button
              key={s}
              className={`hyp-filter-btn ${filter === s ? 'active' : ''}`}
              onClick={() => setFilter(s)}
            >
              {s === 'ALL' ? `All (${hypotheses.length})` : `${s} (${statusCounts[s] || 0})`}
            </button>
          ))}
        </div>
      </div>

      <div className="hyp-layout">
        <div className="hyp-list">
          {filtered.length === 0 ? (
            <div className="hyp-empty">
              <div className="hyp-empty-icon">🔬</div>
              <p>No hypotheses match your filters.</p>
              <p className="hyp-empty-hint">Hypotheses are generated by the AI analysis module during scans.</p>
            </div>
          ) : (
            filtered.map(h => (
              <div
                key={h.id}
                className={`hyp-card ${selectedHypothesis?.id === h.id ? 'selected' : ''}`}
                onClick={() => setSelectedHypothesis(h)}
              >
                <div className="hyp-card-header">
                  <span className="hyp-card-title">{h.title}</span>
                  <span
                    className="hyp-status-badge"
                    style={{ background: STATUS_COLORS[h.status] || '#6b7280' }}
                  >
                    {h.status}
                  </span>
                </div>
                <div className="hyp-card-meta">
                  <span className="hyp-source">{SOURCE_LABELS[h.source] || h.source}</span>
                  <span className="hyp-conf">
                    Confidence: <strong>{(h.confidence * 100).toFixed(0)}%</strong>
                    <span className="hyp-conf-bar">
                      <span style={{ width: `${h.confidence * 100}%`, background: confidenceColor(h.confidence) }} />
                    </span>
                  </span>
                </div>
                <p className="hyp-card-desc">{h.description.slice(0, 120)}{h.description.length > 120 ? '…' : ''}</p>
                <div className="hyp-card-time">{new Date(h.created_at).toLocaleString()}</div>
              </div>
            ))
          )}
        </div>

        {selectedHypothesis && (
          <div className="hyp-detail">
            <div className="hyp-detail-header">
              <h3>{selectedHypothesis.title}</h3>
              <button className="hyp-close-btn" onClick={() => setSelectedHypothesis(null)}>✕</button>
            </div>
            <div className="hyp-detail-meta">
              <span
                className="hyp-status-badge large"
                style={{ background: STATUS_COLORS[selectedHypothesis.status] || '#6b7280' }}
              >
                {selectedHypothesis.status}
              </span>
              <span className="hyp-source">{SOURCE_LABELS[selectedHypothesis.source] || selectedHypothesis.source}</span>
              <span className="hyp-conf-label">
                Confidence: {(selectedHypothesis.confidence * 100).toFixed(0)}%
              </span>
            </div>

            <div className="hyp-detail-section">
              <h4>Description</h4>
              <p>{selectedHypothesis.description}</p>
            </div>

            <div className="hyp-detail-section">
              <h4>Scan ID</h4>
              <code>{selectedHypothesis.scan_id}</code>
            </div>

            <div className="hyp-detail-section">
              <h4>Generated At</h4>
              <p>{new Date(selectedHypothesis.created_at).toLocaleString()}</p>
            </div>

            <div className="hyp-detail-warning">
              ⚠️ This is an unverified hypothesis. It must not be reported as a confirmed vulnerability without evidence-backed verification.
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function confidenceColor(conf: number): string {
  if (conf >= 0.8) return '#dc2626'
  if (conf >= 0.6) return '#d97706'
  return '#6b7280'
}
