# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/v1/ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai/v1/ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61i/v1/ai.proto\x12\x05\x61i.v1\"\x0f\n\rHealthRequest\"V\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x13\n\x0binitialized\x18\x04 \x01(\x08\"s\n\x0e\x46indingSummary\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x1a\n\x12vulnerability_type\x18\x03 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"\xe0\x01\n\x1fGenerateExecutiveSummaryRequest\x12\x12\n\ntarget_url\x18\x01 \x01(\t\x12\x12\n\nhigh_count\x18\x02 \x01(\x05\x12\x14\n\x0cmedium_count\x18\x03 \x01(\x05\x12\x11\n\tlow_count\x18\x04 \x01(\x05\x12\x12\n\ninfo_count\x18\x05 \x01(\x05\x12\'\n\x08\x66indings\x18\x06 \x03(\x0b\x32\x15.ai.v1.FindingSummary\x12\x10\n\x08\x64uration\x18\x07 \x01(\t\x12\x1d\n\x15\x64\x65tected_technologies\x18\x08 \x01(\t\"e\n GenerateExecutiveSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x13\n\x0brisk_rating\x18\x02 \x01(\t\x12\x1b\n\x13key_recommendations\x18\x03 \x03(\t2\xaf\x01\n\tAiService\x12\x35\n\x06Health\x12\x14.ai.v1.HealthRequest\x1a\x15.ai.v1.HealthResponse\x12k\n\x18GenerateExecutiveSummary\x12&.ai.v1.GenerateExecutiveSummaryRequest\x1a\'.ai.v1.GenerateExecutiveSummaryResponseB5Z3github.com/parth/lastresort/internal/gen/ai/v1;aiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.v1.ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/parth/lastresort/internal/gen/ai/v1;aiv1'
  _globals['_HEALTHREQUEST']._serialized_start=25
  _globals['_HEALTHREQUEST']._serialized_end=40
  _globals['_HEALTHRESPONSE']._serialized_start=42
  _globals['_HEALTHRESPONSE']._serialized_end=128
  _globals['_FINDINGSUMMARY']._serialized_start=130
  _globals['_FINDINGSUMMARY']._serialized_end=245
  _globals['_GENERATEEXECUTIVESUMMARYREQUEST']._serialized_start=248
  _globals['_GENERATEEXECUTIVESUMMARYREQUEST']._serialized_end=472
  _globals['_GENERATEEXECUTIVESUMMARYRESPONSE']._serialized_start=474
  _globals['_GENERATEEXECUTIVESUMMARYRESPONSE']._serialized_end=575
  _globals['_AISERVICE']._serialized_start=578
  _globals['_AISERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
