# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai.v1 import ai_pb2 as ai_dot_v1_dot_ai__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai/v1/ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeRecon = channel.unary_unary(
                '/ai.v1.AiService/AnalyzeRecon',
                request_serializer=ai_dot_v1_dot_ai__pb2.AnalyzeReconRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.AnalyzeReconResponse.FromString,
                _registered_method=True)
        self.GenerateHypotheses = channel.unary_unary(
                '/ai.v1.AiService/GenerateHypotheses',
                request_serializer=ai_dot_v1_dot_ai__pb2.GenerateHypothesesRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GenerateHypothesesResponse.FromString,
                _registered_method=True)
        self.ScoreConfidence = channel.unary_unary(
                '/ai.v1.AiService/ScoreConfidence',
                request_serializer=ai_dot_v1_dot_ai__pb2.ScoreConfidenceRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.ScoreConfidenceResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ai.v1.AiService/Health',
                request_serializer=ai_dot_v1_dot_ai__pb2.HealthRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GenerateFindingNarrative = channel.unary_unary(
                '/ai.v1.AiService/GenerateFindingNarrative',
                request_serializer=ai_dot_v1_dot_ai__pb2.GenerateFindingNarrativeRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GenerateFindingNarrativeResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeRecon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateHypotheses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreConfidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFindingNarrative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeRecon': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeRecon,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.AnalyzeReconRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.AnalyzeReconResponse.SerializeToString,
            ),
            'GenerateHypotheses': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHypotheses,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GenerateHypothesesRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GenerateHypothesesResponse.SerializeToString,
            ),
            'ScoreConfidence': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreConfidence,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.ScoreConfidenceRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.ScoreConfidenceResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.HealthRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.HealthResponse.SerializeToString,
            ),
            'GenerateFindingNarrative': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFindingNarrative,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GenerateFindingNarrativeRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GenerateFindingNarrativeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeRecon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/AnalyzeRecon',
            ai_dot_v1_dot_ai__pb2.AnalyzeReconRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.AnalyzeReconResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateHypotheses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/GenerateHypotheses',
            ai_dot_v1_dot_ai__pb2.GenerateHypothesesRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GenerateHypothesesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreConfidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/ScoreConfidence',
            ai_dot_v1_dot_ai__pb2.ScoreConfidenceRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.ScoreConfidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/Health',
            ai_dot_v1_dot_ai__pb2.HealthRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFindingNarrative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/GenerateFindingNarrative',
            ai_dot_v1_dot_ai__pb2.GenerateFindingNarrativeRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GenerateFindingNarrativeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
